name: scandit_flutter_datacapture_id_europe_driving_license
description: ScanditIdEuropeDrivingLicense is a library that enables decoding of the back of European driving licenses.
version: 7.4.0
homepage: https://scandit.com

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.id_europe_driving_license
        pluginClass: ScanditFlutterDataCaptureIdEuropeDrivingLicensePlugin
      ios:
        pluginClass: ScanditFlutterDatacaptureIdEuropeDrivingLicensePlugin
